image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x ./artifacts/app-card-delivery.jar
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info "-Dselenide.headless=true"
