image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x app-ibank-build-for-testers.jar
  - java -jar app-ibank-build-for-testers.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info "-Dselenide.headless=true"
